spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jt?useSSL=false&rewriteBatchedStatements=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123@abc
    driver-class-name: com.mysql.cj.jdbc.Driver
